import { defineConfig } from 'vite'
import { copyFileSync, existsSync } from 'fs'

const isProd = process.env.NODE_ENV === 'production'

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugins github repository
*/
`

export default defineConfig({
  plugins: [],
  build: {
    target: 'es2018',
    lib: {
      entry: 'src/main.js',
      formats: ['cjs'],
      fileName: () => 'main.js'
    },
    rollupOptions: {
      external: ['obsidian'],
      output: {
        banner,
        exports: 'named',
        globals: {
          obsidian: 'obsidian'
        },
        assetFileNames: 'styles.css'
      },
      watch: {
        exclude: ['main.js', 'styles.css']
      }
    },
    outDir: './',
    emptyOutDir: false,
    sourcemap: isProd ? false : 'inline',
    minify: isProd
  },
  define: {
    global: 'globalThis'
  }
})