import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import { copyFileSync } from 'fs'

const isProd = process.env.NODE_ENV === 'production'

const banner = 
`/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source visit the plugins github repository
*/
`

// Plugin to copy main.js to root after build
const copyPlugin = () => ({
  name: 'copy-main',
  writeBundle() {
    try {
      copyFileSync('./dist/main.js', './main.js')
      console.log('✓ Copied main.js to root directory')
    } catch (err) {
      console.error('Failed to copy main.js:', err)
    }
  }
})

export default defineConfig({
  plugins: [vue(), copyPlugin()],
  build: {
    target: 'es2018',
    lib: {
      entry: 'src/main.js',
      formats: ['cjs'],
      fileName: () => 'main.js'
    },
    rollupOptions: {
      external: ['obsidian'],
      output: {
        banner,
        exports: 'named',
        globals: {
          obsidian: 'obsidian'
        }
      }
    },
    outDir: './dist',
    emptyOutDir: true,
    sourcemap: isProd ? false : 'inline',
    minify: isProd
  },
  define: {
    global: 'globalThis'
  }
})